version: "3.3"

services:
  database:
    image: postgres:latest
    working_dir: /src
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ".:/src"
    ports:
      - "8003:5432"
  webservice:
    image: nginx:alpine
    working_dir: /src
    volumes:
      - ".:/src"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    image: daferreira/php:8.1
    build: phpdocker/php-fpm
    working_dir: /src
    environment:
      DB_DATABASE: database
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: localhost
      DB_DRIVER: pdo_pgsql
      DB_CHARSET: utf8mb4
      DB_PORT: 5432
      UID: 1000
      GID: 1000
      UNAME: user
    volumes:
      - ".:/src"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini"
    depends_on:
      - database